### ISSUE TITLE
rustfmt breaks code using try! macro

### ISSUE THREAD

**Issue by sphinxc0re** [rust-lang-nursery/rustfmt#1444]
When formatting with rustfmt, code using the `try!` macro is being broken. Here an example:
```rust
try!(
  match self {
    &Statement {
      op: Operation::Add(ref a, ref b),
      ref assignee,
    } => typecheck_binop(a, b, assignee),
    // more code
    
    // even more code
  },   // <----- This comma is added by rustfmt breaking my code
);
```

My configuration:
```toml
max_width = 1000
fn_call_width = 1000
chain_one_line_max = 100
reorder_imports = true
reorder_imported_names = true
fn_call_style = "Block"

```
