### ISSUE TITLE
Line length not respected on match arms that return strings.

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rustfmt#1493]
Given:

<details>

```rust
impl error::Error for Error {
    fn cause(&self) -> Option<&error::Error> {
        None
    }

    fn description(&self) -> &'static str {
        match *self {
            Error::NoLayoutForOpaqueBlob => {
                "Tried to generate an opaque blob, but had no layout"
            }
            Error::InstantiationOfOpaqueType => {
                "Instantiation of opaque template type or partial template \
                 specialization"
            }
        }
    }
}
```

</details>

With the following config (taken straight from bindgen):

<details>

```toml
max_width = 80
format_strings = false
fn_brace_style = "SameLineWhere"
item_brace_style = "SameLineWhere"
struct_lit_multiline_style = "ForceMulti"
where_trailing_comma = true
reorder_imports = true
reorder_imported_names = true
normalize_comments = false
write_mode = "Overwrite"
```

</details>

Rustfmt yields:

<details>

```rust
impl error::Error for Error {
    fn cause(&self) -> Option<&error::Error> {
        None
    }

    fn description(&self) -> &'static str {
        match *self {
            Error::NoLayoutForOpaqueBlob => "Tried to generate an opaque blob, but had no layout",
            Error::InstantiationOfOpaqueType => {
                "Instantiation of opaque template type or partial template \
                 specialization"
            }
        }
    }
}
```

</details>

(Note how the `Error::NoLayoutForOpaqueBlob` branch was previously compliant with the coding style, and after formatting isn't)
