### ISSUE TITLE
Bracing options for modules

### ISSUE THREAD

**Issue by TimBednarzyk** [rust-lang-nursery/rustfmt#1763]
There should be an option to configure the brace style for modules just like `control_brace_style`, `fn_brace_style`, and `item_brace_style`.

Currently, only the following is possible:
```rust
#[cfg(test)]
mod tests {
  #[test]
  fn it_works()
  {
  }
}
```

However, if there was a `mod_brace_style` then there could be an option for `"AlwaysNextLine"` which makes the above code look like the following:
```rust
#[cfg(test)]
mod tests
{
  #[test]
  fn it_works()
  {
  }
}
```

**Comment by nrc** [comment]
A module is just an item, so module bracing should be dictated by `item_brace_style`.

**Comment by TimBednarzyk** [comment]
This is the contents of the `rustfmt.toml` that resulted in the former block of code:
```toml
control_brace_style = "AlwaysNextLine"
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"
tab_spaces = 2
```
