### ISSUE TITLE
rustfmt inserts newline between comment and `use` when both `reorder_imports` and `reorder_imports_in_group` is set to `true`

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#1789]
rustfmt.toml
```toml
reorder_imports = true
reorder_imports_in_group = true
```
input
```rust
// cmp
use std::cmp;
use std::cmp::{max, min, Ordering};
```
output
```rust
// cmp

use std::cmp;
use std::cmp::{max, min, Ordering};
```
