### ISSUE TITLE
#[derive(...)] attributes being formatted longer than max_width

### ISSUE THREAD

**Issue by radix** [rust-lang-nursery/rustfmt#1941]
rustfmt version: `0.2.4-nightly ( )` (I updated it yesterday or the day before)

```toml
chain_one_line_max = 100
fn_args_density = "Compressed"
fn_call_width = 100
max_width = 100
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 2
```

```rust
#[derive(Add, Sub, Mul, Div, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Debug, Hash,
Serialize, Deserialize)]
pub struct HP(pub u8);
```

rustfmt is putting the `Serialize, Deserialize)]` line line back at the end of the first line, but that's longer than 100 characters so it then warns that it produced a line that is too long. I believe that this is a regression from an earlier version.
