### ISSUE TITLE
Confusing spread of width configurations

### ISSUE THREAD

**Issue by alexheretic** [rust-lang-nursery/rustfmt#1984]
It is great that rustfmt is configurable, however I found the amount of width configurations & defaults initially confusing. I expected the fmt rules to work on a single max width, so all wrapping logic would work against that. 

I actually avoided using rustfmt for a while, as I mistakenly thought it couldn't handle one-line struct patterns etc. Now I realise it *can*, but has a separate width to keep to. Silly me. But perhaps this can be simpler?

After grepping through the docs I now have, for my personal projects
```toml
array_width = 100
chain_one_line_max = 100
comment_width = 100
max_width = 100
fn_call_width = 100
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
# other rules
```
Which seems to work for now, so thank you. However, this also seems a little fragile & ugly. I'd really prefer to declare it once, perhaps having all rules match `max_width` unless explicitly configured otherwise.

Or some new rule:
```toml
max_width_that_applies_to_everything_and_causes_errors_if_you_try_to_use_the_other_ones = 100
```

**Comment by nrc** [comment]
cc #1974 

I think whatever happens, we keep `max_width`

One approach for the others might be to have a single option - `short_heuristic: bool` which uses the default widths if `true` (default`) and `max_width` if `false`. If we want to be a little more fine-grained we could have `short_expr_heuristic` and `short_item_heursitic`.

**Comment by alexheretic** [comment]
Yes I could deal with that. Although that name doesn't jump out at me as meaning what you describe. I do like a readable property name that I don't need to lookup. 

```toml
max_width = 101
all_widths_use_max_width = true  # proposed
```
We already have fine grain control with all the other rules.

I would also suggest making sure the other rules end in `width` or are otherwise easily identifiable, and to reference all the rules in documentation of any of them (or just `max_width`). It makes sense that if I wanted to change one width, I'm probably interested in the others.
