### ISSUE TITLE
Strange trailing commas in closures returning a literal string

### ISSUE THREAD

**Issue by mathstuf** [rust-lang-nursery/rustfmt#2135]
Not sure what's up with this diff from `rustfmt`:

```diff
-                .chain_err(|| {
-                    "failed to construct merge-base command for submodule conflict resolution"
-                })?;
+                .chain_err(
+                    || "failed to construct merge-base command for submodule conflict resolution",
+                )?;
```

Note the trailing comma at the end of the string literal on the `+` side of the diff. The configuration I'm using:

```toml
attributes_on_same_line_as_field = false                                                                                                                                                              
attributes_on_same_line_as_variant = false
chain_split_single_child = true
match_block_trailing_comma = true
multiline_closure_forces_block = true
multiline_match_arm_forces_block = true
normalize_comments = true
remove_blank_lines_at_start_or_end_of_block = true
reorder_imports = true
reorder_imports_in_group = true
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
single_line_if_else_max_width = 0
struct_field_align_threshold = 0
struct_lit_multiline_style = "PreferSingle"
struct_variant_width = 0
use_try_shorthand = true
```
