### ISSUE TITLE
broken `--package` filter in 0.2.17-nightly

### ISSUE THREAD

**Issue by davemilter** [rust-lang-nursery/rustfmt#2241]
Before `0.2.17-nightly` for package like this:

```toml
[package]
name = "foo"
version = "0.0.1"
authors = ["author <author@mail.com>"]

[lib]
name = "foo_core"
crate-type = ["cdylib"]
```

I was able to check format of only this package with such command:
```sh
cargo +nightly fmt --package=foo -- --write-mode diff
```

but at now (0.2.17-nightly) it reports error:

```
package `foo` is not a member of the workspace
```

which is wrong, but such commands works:

```sh
cargo +nightly fmt --package=foo_core -- --write-mode diff
```

what is really wrong, because of `foo_core` is not part of workspace,
it is just name of library.
