### ISSUE TITLE
Running rustfmt in Travis

### ISSUE THREAD

**Issue by orenbenkiki** [rust-lang-nursery/rustfmt#2285]
I've just tried adding `cargo fmt -- --write-mode diff` in Travis, following the example in the README.
 I get the error `This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.`. This happens even when using the nightly rust.

I tried various ways of getting Travis to install/use the right `rustfmt` version. I have seen all sort of other incantations in different projects but none worked for me.

Either I'm doing something wrong...

Or the README example should be improved to describe the correct way to use `rustfmt` in Travis (if it makes a difference, when using nightly, stable, or a specific rust version).

**Comment by nrc** [comment]
You need to install the rustfmt-nightly crate, not the rustfmt crate. I've updated the README.md to fix the `cargo install` command.

**Comment by orenbenkiki** [comment]
I must be doing something wrong then.

My `.travis.yml` looks like this (taken from the updated README):
```yaml
# Rust project
language: rust
cache: cargo

rust:
- 1.21.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1

before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt-nightly

script:
- cargo fmt -- --write-mode=diff
- cargo build --verbose
- cargo test --verbose
```

And I still get the error (see https://travis-ci.org/orenbenkiki/loggy/builds/316871482 for example).
