### ISSUE TITLE
long attributes should be multi-lined

### ISSUE THREAD

**Issue by jkcclemens** [rust-lang-nursery/rustfmt#2620]
Before I ran rustfmt, I had this code. I expected a trailing comma to be added to `job` and after `parse(try_from_str)`.

```rust
#[derive(Debug, StructOpt)]
#[structopt(about = "Display information about the character on FF Logs")]
pub struct Params {
  #[structopt(help = "The server the character is on")]
  server: String,
  #[structopt(help = "The character's first name")]
  first_name: String,
  #[structopt(help = "The character's last name")]
  last_name: String,
  #[structopt(
    short = "j",
    long = "job",
    help = "The job to look at",
    parse(try_from_str)
  )]
  job: Option<Job>
}
```

After running rustfmt:

```rust
#[derive(Debug, StructOpt)]
#[structopt(about = "Display information about the character on FF Logs")]
pub struct Params {
  #[structopt(help = "The server the character is on")]
  server: String,
  #[structopt(help = "The character's first name")]
  first_name: String,
  #[structopt(help = "The character's last name")]
  last_name: String,
  #[structopt(short = "j", long = "job", help = "The job to look at", parse(try_from_str))]
  job: Option<Job>,
}
```

Notice that the structopt attribute on `job` has been condensed. This makes it much harder to read and much harder to edit.

```toml
unstable_features = true

indent_style = "block"

max_width = 120

wrap_comments = true
comment_width = 120
normalize_comments = true

format_strings = true

hard_tabs = false
tab_spaces = 2

merge_imports = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true

match_block_trailing_comma = true

use_field_init_shorthand = true
use_try_shorthand = true
```

Is this intended behavior, and can I turn it off if it is?
