### ISSUE TITLE
Weird struct alignment

### ISSUE THREAD

**Issue by Ekleog** [rust-lang-nursery/rustfmt#2633]
With this as `.rustfmt.toml`:
```toml
format_strings = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 5
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
```

`rustfmt 0.4.2-nightly (dd807e2 2018-04-18)` puts forward the following diff:
```diff
 #[derive(Fail, Debug, Clone)]
 pub enum BuildError {
-    LineTooLong { length: usize, limit: usize },
-    DisallowedByte { b: u8, pos: usize },
+    LineTooLong { length: usize, limit:  usize },
+    DisallowedByte { b:   u8, pos: usize },
     ContainsNewLine { pos: usize },
 }
```

I guess the `struct`-like elements inside the `enum` is putting `rustfmt` off the track?

Hope that helps, and thanks for your work!
