### ISSUE TITLE
`reorder_impl_items` flip-flopping

### ISSUE THREAD

**Issue by Ekleog** [rust-lang-nursery/rustfmt#2634]
I have this `.rustfmt.toml`:
```toml
format_strings = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 5
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
```

When I run `cargo fmt --all` (`rustfmt 0.4.2-nightly (dd807e2 2018-04-18)`), I get the following diff:
```diff
@@ -31,10 +31,6 @@ pub enum Command<'a> {
 }
 
 impl<'a> Command<'a> {
-    pub fn parse(arg: &[u8]) -> Result<Command, ParseError> {
-        nom_to_result(command(arg))
-    }
-
     pub fn send_to(&self, w: &mut io::Write) -> io::Result<()> {
         match self {
             &Command::Data(ref c) => c.send_to(w),
@@ -50,6 +46,10 @@ impl<'a> Command<'a> {
             &Command::Vrfy(ref c) => c.send_to(w),
         }
     }
+
+    pub fn parse(arg: &[u8]) -> Result<Command, ParseError> {
+        nom_to_result(command(arg))
+    }
 }
 
 named!(pub command(&[u8]) -> Command, alt!(
```

However, if I run it a second time, the diff is canceled. A third time, it appears again.

IOW, I think it just swaps the functions around every time.

Hope that helps and thanks for your work!
