### ISSUE TITLE
`imports_layout = "Mixed"` ignored

### ISSUE THREAD

**Issue by Ekleog** [rust-lang-nursery/rustfmt#2635]
I have the following `.rustfmt.toml`:
```toml
format_strings = true
merge_imports = true
normalize_comments = true
struct_field_align_threshold = 5
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true

imports_layout = "Mixed"
```
(added `imports_layout = "Mixed"` so as to be sure that the issue is not just documentation being wrong in the default value of the option)

With `rustfmt 0.4.2-nightly (dd807e2 2018-04-18)`, I get the following diff:
```diff
 use nom::IResult;
-use std::{fmt, io, str};
-use std::str::FromStr;
+use std::{fmt,
+          io,
+          str::{self, FromStr}};
 
 use helpers::*;
```

I'd have expected the result to look like:
```rust
use std::{fmt, io, str::{self, FromStr}};
```
due to the `"Mixed"` option.

Hope that helps and thanks for your work!
