### ISSUE TITLE
Support linebroken import lists

### ISSUE THREAD

**Issue by bluss** [rust-lang-nursery/rustfmt#788]
rustfmt wanted to make this change (and many larger, just like this). I'd like to have an option to **_not do**_ this, to preserve the list formatting, with trailing comma, so that the code is easy to read and edit.

``` diff
@@ -1,22 +1,19 @@
 use std::fmt;
-use super::{
-    ArrayBase,
-    Data,
-    Dimension,
-};
+use super::{ArrayBase, Data, Dimension};


@@ -87,14 +80,8 @@ pub use stride_error::StrideError;
 pub use si::{Si, S};

 use iterators::Baseiter;
-pub use iterators::{
-    InnerIter,
-    InnerIterMut,
-    OuterIter,
-    OuterIterMut,
-    AxisChunksIter,
-    AxisChunksIterMut,
-};
+pub use iterators::{InnerIter, InnerIterMut, OuterIter, OuterIterMut,
+                    AxisChunksIter, AxisChunksIterMut};

```

If you're curious, these are my settings:

``` toml
ideal_width = 80
max_width = 85
fn_call_width = 80
fn_return_indent = "WithWhereClause"
fn_args_density = "Compressed"
normalise_comments = false
where_density = "Tall"
```
