### ISSUE TITLE
Write mode is not being used.

### ISSUE THREAD

**Issue by carlosgaldino** [rust-lang-nursery/rustfmt#794]
Hi,

I have a `rustfmt.toml` with: 

```toml
reorder_imports = true
write_mode = "Overwrite"
```

When I run `fmt` either with `cargo fmt` or `rustfmt` directly the backup files are still created. I already tried to change to `write_mode = "overwrite"` and the same thing happens. The config file is being read though since `reorder_imports = true` works.

Is this a known bug or am I doing something wrong?

Thanks.

P.S.: I'm using `rustfmt` v0.2.1.
